'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Comet_OS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1_space_invaders() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_space_invaders", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property _1349020582_monotone_wrench_settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1349020582_monotone_wrench_settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1366077992_51669() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1366077992_51669", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6329() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6329", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property About_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("About-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_edit_clear_locationbar_ltr_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions-edit-clear-locationbar-ltr-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property appbinclick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appbinclick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property appbinrollover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appbinrollover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property black_textures_hd_background_squares_210945() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("black-textures-hd-background-squares-210945", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bobines_video_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bobines-video-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property camera_b1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("camera_b1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property camera_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("camera-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property camera_j6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("camera_j6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comet_OS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comet_OS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CometOSDesktop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CometOSDesktop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CometOSDesktop1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CometOSDesktop1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CometOSLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CometOSLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CometOSLogo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CometOSLogo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CometOSMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CometOSMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CometOSmnts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CometOSmnts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Danrabbit_Elementary_Folder_grey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Danrabbit-Elementary-Folder-grey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dark_Gradient_Wallpaper_1920x1200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dark_Gradient_Wallpaper-1920x1200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property darkWindowdesktop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("darkWindowdesktop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property desktop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desktop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DSC06239() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DSC06239", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Email_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Email-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Email_2561() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Email-2561", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Everaldo_Crystal_Clear_Mimetype_font_bitmap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Everaldo-Crystal-Clear-Mimetype-font-bitmap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (1)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__10_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (10)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__3_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (3)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__5_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (5)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__5_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (5)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__5_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (5)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__6_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (6)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__6_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (6)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__6_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (6)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__7_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (7)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon__9_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon (9)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_grey_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder-grey-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_grey_icon2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder_grey_icon2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folders_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folders-open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fullscreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fullscreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fullscreen_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fullscreen_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fullscreen1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fullscreen1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property goBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property goForward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goForward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property goForward1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goForward1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gradient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gradient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gradient_wallpaper_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gradient-wallpaper-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gradient_wallpaper_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gradient-wallpaper-31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gradient_wallpaper_311() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gradient-wallpaper-311", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gradient1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gradient1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gradient3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gradient3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gradient4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gradient4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gradientclick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gradientclick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property homeSweetHome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("homeSweetHome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property k_snap_shot_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("k-snap-shot-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MenuBar3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuBar3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimalistic_orange_gradient_desktop_2560x1600_hd_wallpaper_892507() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimalistic_orange_gradient_desktop_2560x1600_hd-wallpaper-892507", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monotone_cog_settings_gear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monotone_cog_settings_gear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property moon_768x1366() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moon-768x1366", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property n4rmCt2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("n4rmCt2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_document_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Actions-document-open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Devices_media_floppy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Devices-media-floppy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Places_folder_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Places-folder-blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property removeTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("removeTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rotating_earth__large_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rotating_earth__large_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saturn_wallpaper_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saturn_wallpaper_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sysMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sysMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_align_center_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text-align-center-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_align_left_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text-align-left-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_align_right_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text-align-right-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property the_starry_night_wallpaper_1366x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("the_starry_night-wallpaper-1366x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vista_bar_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vista_bar_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
